description: "Gatsby Mail is an example mail application built with modern tech many of us love: React, GraphQL, and more... all powered by Gatsby!"
url: "https://gatsby-mail.netlify.com"
twitter: "@gatsbyjs"
